# Generated by Django 5.2.1 on 2025-07-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameviewlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_logs",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="gamegenre",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="genre_games", to="games.genre"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(related_name="games", through="games.GameGenre", to="games.genre"),
        ),
        migrations.AddField(
            model_name="like",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="liked_by_users", to="games.game"
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="users.user"),
        ),
        migrations.AddField(
            model_name="review",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reviewed_by_users", to="games.game"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="users.user"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gamegenre",
            unique_together={("game", "genre")},
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "game")},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "game")},
        ),
    ]
