# Generated by Django 5.2.4 on 2025-08-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_initial"),
        ("users", "0007_remove_user_preferred_genres_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "카테고리",
                "verbose_name_plural": "카테고리 목록",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="GameCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="game_categories", to="games.category"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="category_games", to="games.game"
                    ),
                ),
            ],
            options={
                "verbose_name": "게임 카테고리",
                "verbose_name_plural": "게임 카테고리",
                "db_table": "game_category",
                "unique_together": {("category", "game")},
            },
        ),
        migrations.DeleteModel(
            name="PlaytimeCategory",
        ),
        migrations.AddField(
            model_name="game",
            name="categories",
            field=models.ManyToManyField(related_name="games", through="games.GameCategory", to="games.category"),
        ),
    ]
