# Generated by Django 5.2.4 on 2025-08-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_category_gamecategory_delete_playtimecategory_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["-like_count", "-average_rating"], name="game_like_co_d694b1_idx"),
        ),
    ]
