# Generated by Django 5.2.4 on 2025-08-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_game_like_co_d694b1_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["-created_at"], name="game_created_1381fa_idx"),
        ),
    ]
