services:
  django:
    container_name: django-boardq
    env_file:
      - envs/.local.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    build:
      context: .
    working_dir: /boardq
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --workers 3 --bind 0.0.0.0:8000 config.wsgi:application"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/boardq/static
      - media_volume:/boardq/media
    networks:
      - ws
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx-boardq
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    volumes:
      - ./resources/nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/boardq/static
      - media_volume:/boardq/media
    networks:
      - ws

  db:
    image: postgres:14
    container_name: postgres-boardq
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw1234
      POSTGRES_ROOT_USER: postgres
      POSTGRES_DB: boardq
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ws
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis/redis-stack:latest
    container_name: redis-boardq
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - ws
    healthcheck:
      test: [ "CMD", "redis-cli", "ping","-p","6379" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  celery:
    container_name: celery_service # 컨테이너 이름
    image: boardgame-django # Django 앱의 Docker 이미지를 재사용
    env_file: # django 서비스와 동일하게 env_file 사용
      - envs/.local.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local # Django 설정 모듈 명시
      # DB 및 RabbitMQ 환경 변수는 env_file에서 로드되거나 Redis를 브로커로 사용하므로 제거
    working_dir: /boardq # django 서비스의 working_dir에 맞춰 작업 디렉토리 설정
    command: >
      bash -c "poetry run celery -A config worker -l info"

    depends_on:
      django:
        condition: service_started # Django 서비스가 시작된 후 Celery가 시작되도록 의존성 설정
      redis:
        condition: service_healthy # Redis 서비스가 healthy 상태인 후 Celery가 시작되도록 의존성 설정

    networks: # <--- 이 부분 추가
        - ws

networks:
  ws:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data: