# Generated by Django 5.2.1 on 2025-07-25 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("nickname", models.CharField(help_text="2-20 characters", max_length=20, unique=True)),
                ("birth", models.DateTimeField()),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "role",
                    models.CharField(choices=[("user", "User"), ("admin", "Admin")], default="user", max_length=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended"), ("deleted", "Deleted")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="UserPreferencePlaytime",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to="users.user"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "playtime_category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.playtimecategory"),
                ),
            ],
            options={
                "verbose_name": "선호하는 게임 시간",
                "verbose_name_plural": "선호하는 게임 시간 목록",
                "db_table": "user_preference_playtime",
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                ("social_id", models.AutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(help_text='e.g., "google"', max_length=50)),
                ("provider_id", models.CharField(help_text="Google user ID", max_length=255)),
                (
                    "profile_url",
                    models.CharField(blank=True, help_text="Profile picture URL", max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
            options={
                "verbose_name": "소셜 어카운트",
                "verbose_name_plural": "소셜 어카운트 목록",
                "db_table": "social_account",
                "unique_together": {("provider", "provider_id")},
            },
        ),
        migrations.CreateModel(
            name="UserPreferenceGenre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("genre", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.genre")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
            options={
                "verbose_name": "사용자 선호하는 장르",
                "verbose_name_plural": "사용자 선호하는 장르 목록",
                "db_table": "user_preference_genre",
                "unique_together": {("user", "genre")},
            },
        ),
    ]
