# Generated by Django 5.2.4 on 2025-08-05 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDeletionReason",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DISSATISFIED", "서비스에 만족하지 않음"),
                            ("NO_FEATURES", "원하는 기능이나 콘텐츠가 없음"),
                            ("TOO_MANY_ERRORS", "사용이 불편하거나 오류가 많음"),
                            ("NO_LONGER_NEEDED", "더 이상 사용할 일이 없음"),
                            ("DUPLICATE_ACCOUNT", "계정을 중복으로 생성함"),
                            ("OTHER", "기타 (직접 입력)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("additional_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_reason",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "회원 탈퇴 사유",
                "verbose_name_plural": "회원 탈퇴 사유 목록",
                "db_table": "account_deletion_reason",
            },
        ),
    ]
