# Generated by Django 5.2.4 on 2025-08-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="suspended_until",
            field=models.DateTimeField(blank=True, help_text="사용자 차단 기간 (NULL이면 영구 정지)", null=True),
        ),
    ]
