# Generated by Django 5.2.4 on 2025-08-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_accountdeletionreason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="preferred_genres",
        ),
        migrations.AlterUniqueTogether(
            name="userpreferenceplaytime",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userpreferenceplaytime",
            name="playtime_category",
        ),
        migrations.RemoveField(
            model_name="userpreferenceplaytime",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferred_playtimes",
        ),
        migrations.DeleteModel(
            name="UserPreferenceGenre",
        ),
        migrations.DeleteModel(
            name="UserPreferencePlaytime",
        ),
    ]
