# Generated by Django 5.2.4 on 2025-08-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_preferred_genres_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth",
            field=models.DateField(),
        ),
    ]
